# Generated by Django 2.2.4 on 2019-08-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(default='SOME STRING', max_length=140),
        ),
    ]
