# Generated by Django 2.2.4 on 2019-08-21 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0002_employee_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emess',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(default=' ', max_length=140),
        ),
    ]
